groups:
    - personal
    - work
recipes:
    mac_os_x:
        - sudoalt::default
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::set_computer_name
    attributes:
    osxdefaults:
        computername: T3000
    homebrewalt:
        apps:
        cask_apps:
            - 1password
            - dropbox
            - spotify
            - vlc
            - intellij-idea